### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by RodolfoNV** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-RodolfoNV#1]
https://drive.google.com/file/d/1PZcO92O1eaw0jie-1-l64wTYHjTV8Lie/view?usp=sharing

**Comment by HECTOR-KDM02** [comment]
18 Puntos

Mejorar la coherencia ya que si tiene varia partes sin embargo el orden el vital

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
